FROM maven:3.6.3-openjdk-14 AS build
COPY ./ /app
WORKDIR /app
RUN mvn clean package -U

FROM adopttoopenjdk:14-jre-hotspot
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/api/target/api-1.0-SNAPSHOT.jar /app
EXPOSE 8081

CMD ["java", "-jar", "api-1.0-SNAPSHOT.jar"]