kumuluzee:
  name: calendar-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/bookings-jpa
      connection-url: jdbc:postgresql://localhost:5435/bookings
      username: postgres
      password: postgres

# docker run -d --name rso-bookingsdb -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=bookings -p 5435:5432 --network rso2021 postgres:13