kumuluzee:
  name: calendar-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    consul:
      agent: http://104.45.176.251:8500
  health:
    metrics:
      web-instrumentation:
        - name: calendar-endpoint
          url-pattern: /v1/calendar/*
  rest-client:
    registrations:
      - class: calendar-api
        url: http://localhost:8081/v1/calendar
        read-timeout: 5000
rest-properties:
  maintenance-mode: false
  broken: false
  bookingsurl: http://52.149.170.232:8082/v1/bookings

# docker run -d --name rso-bookingsdb -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=bookings -p 5435:5432 --network rso2021 postgres:13